services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq-acme-pay"
    container_name: "rabbitmq-acme-pay"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data/rabbitmq/data/:/var/lib/rabbitmq"
      - "./data/rabbitmq/log/:/var/log/rabbitmq"
    networks:
      - "rabbitmq"

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    networks: 
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: true
    depends_on:
      - zookeeper

networks:
  kafka-net:
  rabbitmq:
    driver: bridge
