server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  flyway:
    baseline-on-migrate: true
