services:
  postgres-notification:
    image: postgres
    container_name: acme-pay-notification-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notification-service
    volumes:
      - "./data/notification/postgres:/var/lib/postgres/data"
    ports:
      - "5435:5432"
