services:

  notification-service:
    image: acme-pay-notification-service
    container_name: notification-service
    networks:
      - notification-service
      - acme-pay
    environment:
      DB_DATABASE: notification-service
      DB_HOST: notification-service-db
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      SERVER_PORT: 8080
    depends_on:
      - notification-db

  notification-db:
    image: postgres:16
    container_name: notification-service-db
    networks:
      - notification-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "../data/notification/postgresql:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"

networks:
  notification-service:
  acme-pay:
    external: true

