services:
  postgres-notification:
    image: postgres
    container_name: acme-pay-notification-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "./data/notification/postgres:/var/lib/postgres/data"
    ports:
      - "${DB_PORT}:5432"
