services:

  notification-service:
    container_name: notification-service
    image: acme-pay-notification-service:v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - notification-service
      - acme-pay
    environment:
      DB_HOST: notification-service-db
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - notification-db

  notification-db:
    image: postgres:16
    container_name: notification-service-db
    networks:
      - notification-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "./data/notification/postgres:/var/lib/postgres/data"
    ports:
      - "${DB_PORT}:5432"

networks:
  notification-service:
  acme-pay:
    external: true

