services:
  postgres-account:
    image: postgres
    container_name: acme-pay-account-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=account-service
    volumes:
      - "./data/accounts/postgres:/var/lib/postgres/data"
    ports:
      - "5433:5432"
