services:

  account-service:
    image: acme-pay-account-service
    container_name: account-service
    networks:
      - account-service
      - acme-pay
    environment:
      DB_DATABASE: account-service
      DB_HOST: account-service-db
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      SERVER_PORT: 8080
    depends_on:
      - account-db

  account-db:
    image: postgres:16
    container_name: account-service-db
    networks:
      - account-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "../data/accounts/postgresql:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"

networks:
  account-service:
  acme-pay:
    external: true
