server:
  port: ${SERVER_PORT:-8081}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:-postgres}
    username: ${DB_USER:-postgres}
    url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5433}/${DB_DATABASE:-account-service}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  flyway:
    baseline-on-migrate: true
