services:

  customer-service:
    container_name: customer-service
    image: acme-pay-customer-service:v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - customer-service
      - acme-pay
    environment:
      DB_HOST: customer-service-db
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - customer-db

  customer-db:
    image: postgres:16
    container_name: customer-service-db
    networks:
      - customer-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "../data/customer/postgresql:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"

networks:
  customer-service:
  acme-pay:
    external: true
