services:
  postgres-customer:
    image: postgres
    container_name: acme-pay-customer-service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "./data/customer/postgres:/var/lib/postgres/data"
    ports:
      - "${DB_PORT}:5432"
