services:
  gateway-service:
    container_name: gateway-service
    image: acme-pay-gateway-service
    networks:
      - acme-pay
    ports:
      - 8090:8090

networks:
  acme-pay:
    external: true
